# Page settings

baseURL = "https://adityakumar.xyz/resume"
languageCode = "en"
title = "Resume"
theme = "hugo-devresume-theme"






[params]
    author = "Aditya"
    description = "My resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Aditya Kumar"
        tagline = "Computer Science and Engineering Student"
        avatar = "profile-vector-cropped.png"







    [params.contact]
        enable = true
        location = "Mohali"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+91 90643 54247"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "adityakr082@proton.me"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "adityakumar.xyz"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Linux, Git, Docker, PostgreSQL, System Administration, Open Source Collaboration, C/C++/Bash/Java/Rust/Nix/SQL"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication, Team Player, Strong problem solver, Attention to detail"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BE in Computer Science and Engineering"
        university = "Chandigarh University"
        dates = "2020 - present"
        [[params.education.list]]
        degree = "Intermediate (CBSE)"
        university = "DAV Model School"
        dates = "2020"
        [[params.education.list]]
        degree = "Matriculation (CBSE)"
        university = "DAV Model School"
        dates = "2018"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "AWS SAA-CO3"
        body = "Udemy"
        date = "2023"
        [[params.awards.list]]
        name = "Data Mining"
        body = "NPTEL"
        date = "2023"
        [[params.awards.list]]
        name = "Software Testing"
        body = "NPTEL"
        date = "2022"
        [[params.awards.list]]
        name = "Machine Learning"
        body = "Internshala"
        date = "2022"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Seeking a challenging full-time position that utilizes my strong interpersonal skills, excellent time management abilities, and problem-solving expertise in an open-source collaborative environment. Results-driven open-source collaborator with a passion for tackling professional challenges. I have a proven track record of contributing to various projects, including bringing code-server to aarch64, with a particular focus on Android. I have also demonstrated my ability to update documentation and provide support for OpenRC systems. Additionally, I possess experience in creating a Linux distribution from scratch and have successfully deployed projects on websites during a hackathon. I am well-versed in utilizing nix flakes in diverse build environments and have established a personal cloud using Raspberry Pi. My certifications in AWS SAA-C03, data mining, software testing, and machine learning attest to my commitment to continuous learning and professional development."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Code Server"
        meta = "VS Code in a browser"
        tagline = "Create remote development machines so a team can develop from anywhere. Brought official support to aarch64 architecture, mainly on Android platform. Updated documentation to deploy on Android devices. Brought official support to OpenRC systems."

        [[params.projects.list]]
        title = "MyLinux"
        meta = "Operating System"
        tagline = "Created a Linux distribution from scratch using Linux From Scratch (LFS) and Beyond Linux From Scratch (BLFS) guides. Customized the kernel, boot loader, init system, package manager, desktop environment and applications. Tested and debugged the distribution on various hardware and virtual machines."

        [[params.projects.list]]
        title = "NASA International Space Apps Challenge 2022"
        meta = "Hackthon"
        tagline = "Participated in a hackathon with a team of four and developed a web application. Deployed the project on the website using Nginx."

        [[params.projects.list]]
        title = "Home Pi"
        meta = "Personal Cloud using Raspberry Pi"
        tagline = "Set up a personal cloud using Raspberry Pi 4 as the server and Nextcloud as the software platform. Configured the network, firewall, SSL certificates, domain name, backup and security features. Accessed the cloud from various devices and synced files, contacts, calendars, notes and photos."

        [[params.projects.list]]
        title = "Nix Flakes"
        meta = "Reproducible build environment"
        tagline = "Learnt Nix flakes and used them in various build environments such as NixOS, Nixpkgs and Home Manager. Created reproducible and declarative configurations for different systems and projects. Explored the Nix community repositories and contributed to some of them."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Aditya's Blog"
        [[params.information.list.items]]
        details = "Explore a world of tutorials, technical challenges, and solutions in the realm of computer science. Join me on a journey where I share my experiences, insights, and triumphs over various computing hurdles."

[params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "akr2002"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "adityakr082"





